### ISSUE TITLE
PPO can't get body info

### ISSUE THREAD

**Issue by JimLiu1213** [wbap/PyLIS#2]
Hi, 
  I am currently using your repo to do some experiments, but when I was using PPO with rl-baselines3-zoo and multiprocessing, this error showed up: 
```
C:\Users\52302\rl-baselines3-zoo>python train.py --algo ppo --env FoodHuntingHSR-v0 --n-timesteps 1000
pybullet build time: Jun 19 2021 04:01:52
========== FoodHuntingHSR-v0 ==========
Seed: 1992062458
Default hyperparameters for environment (ones being tuned will be overridden):
OrderedDict([('batch_size', 64),
             ('clip_range', 0.2),
             ('ent_coef', 0.0),
             ('gae_lambda', 0.95),
             ('gamma', 0.99),
             ('learning_rate', 0.00025),
             ('n_envs', 8),
             ('n_epochs', 10),
             ('n_steps', 2048),
             ('n_timesteps', 10000000.0),
             ('normalize', True),
             ('policy', 'CnnPolicy')])
Using 8 environments
Overwriting n_timesteps with n=1000
Creating test environment
c:\users\52302\cs285_f2020\gym\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Normalization activated: {'gamma': 0.99, 'norm_reward': False}
Wrapping into a VecTransposeImage
Normalization activated: {'gamma': 0.99}
Wrapping into a VecTransposeImage
Using cpu device
Log path: logs/ppo/FoodHuntingHSR-v0_2
Traceback (most recent call last):
  File "train.py", line 189, in <module>
    exp_manager.learn(model)
  File "C:\Users\52302\rl-baselines3-zoo\utils\exp_manager.py", line 193, in learn
    model.learn(self.n_timesteps, **kwargs)
  File "C:\Python\lib\site-packages\stable_baselines3\ppo\ppo.py", line 308, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "C:\Python\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 234, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "C:\Python\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 175, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "C:\Python\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 162, in step
    return self.step_wait()
  File "C:\Python\lib\site-packages\stable_baselines3\common\vec_env\vec_transpose.py", line 83, in step_wait
    observations, rewards, dones, infos = self.venv.step_wait()
  File "C:\Python\lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 113, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "C:\Python\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 44, in step_wait
    self.actions[env_idx]
  File "C:\Python\lib\site-packages\stable_baselines3\common\monitor.py", line 90, in step
    observation, reward, done, info = self.env.step(action)
  File "c:\users\52302\cs285_f2020\gym\gym\wrappers\time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "c:\users\52302\pylis\gym-foodhunting\gym_foodhunting\foodhunting\gym_foodhunting.py", line 574, in step
    done = self._isDone()
  File "c:\users\52302\pylis\gym-foodhunting\gym_foodhunting\foodhunting\gym_foodhunting.py", line 624, in _isDone
    available_object_ids = [ object_id for object_id in self.object_ids if self._isFood(object_id) ]
  File "c:\users\52302\pylis\gym-foodhunting\gym_foodhunting\foodhunting\gym_foodhunting.py", line 624, in <listcomp>
    available_object_ids = [ object_id for object_id in self.object_ids if self._isFood(object_id) ]
  File "c:\users\52302\pylis\gym-foodhunting\gym_foodhunting\foodhunting\gym_foodhunting.py", line 618, in _isFood
    baseLink, urdfPath = p.getBodyInfo(object_id)
pybullet.error: Couldn't get body info
```

So, may I know what's your settings or any suggestion, please? Some procedures when you did experiment and results would be much appreciated. Thank you. By the way, I am currently using ddpg to run it, and this error is not showing up. So, is it might be a multiprocessing issue?

**Comment by susumuota** [comment]
@JimLiu1213 Thank you for reporting.

I could not reproduce your situation but I updated some code for stable-baselines3 support. I needed to change observation space from [0.0, 1.0] to [0, 255] to use stable-baselines3's CNN policy.

Also there are simple example RL code to learn and play stable-baselines3.
https://github.com/wbap/PyLIS/blob/master/gym-foodhunting/examples/example_rl.py

```
python example_rl.py --env_name=FoodHuntingDiscrete-v0 --total_timesteps=100000 --filename saved_model
python example_rl.py --env_name=FoodHuntingDiscreteGUI-v0 --play --filename saved_model
```

For your case, it looks like a PyBullet's bug if `object_id` is a valid ID. I will test it on multiprocessing env.
```
  File "c:\users\52302\pylis\gym-foodhunting\gym_foodhunting\foodhunting\gym_foodhunting.py", line 618, in _isFood
    baseLink, urdfPath = p.getBodyInfo(object_id)
pybullet.error: Couldn't get body info
```
